version: "3"

services:
  heroes-api:
    image: node:6
    user: "node"
    working_dir: /home/node/app
    environment:
      - PORT=3002
    volumes:
      - ./:/home/node/app
    ports:
      - "3002:3002"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    command: ["node","server.js"]
    # container_name: heroes-api5
    networks:
      - webnet
networks:
  webnet: